shopistan/lazurde-storefront

- components/common/header/index.tsx
- components/common/header/promo-bar/index.tsx
- components/common/header/site-navbar/category-dropdown/index.tsx
- components/common/header/site-navbar/index.tsx
- lib/types/common.ts
feat: added site nav bar in header
> LX-159: added site nav bar in header

- components/common/header/descriptor.js
- components/common/header/site-navbar/index.tsx
chore: updated header descriptor for site nav bar changes
> LW-159: updated header descriptor for site nav bar changes

- components/common/header/index.tsx
- components/common/header/site-navbar/category-dropdown/index.tsx
- components/common/header/site-navbar/category-dropdown/style.module.scss
- components/common/header/site-navbar/index.tsx
- components/common/header/site-navbar/style.module.scss
- lib/types/common.ts
chore: fixed site nav bar styling
> LW-159: fixed site nav bar styling

- components/common/header/site-navbar/index.tsx
> Lw-159: nav bar drop down bug

- components/common/header/site-navbar/category-dropdown/index.tsx
- components/common/header/site-navbar/category-dropdown/style.module.scss
chore: fixed styling for nav bar dropdown
> LW-159: fixed styling for nav bar dropdown

- components/common/header/mobile-navbar/index.tsx
- components/common/header/mobile-navbar/mobile-menu.tsx
- components/common/header/mobile-navbar/mobile-sub-menu.tsx
- components/icons/Bag.tsx
- components/icons/Heart.tsx
> JIRA-00: mobile header props

- components/common/card/index.tsx
- components/common/header/Header.module.css
- components/common/header/descriptor.js
- components/common/header/navbar-lang-selector/style.module.scss
- components/common/header/promo-bar/promo-bar.module.scss
- components/common/header/site-navbar/index.tsx
- components/common/header/site-navbar/style.module.scss
chore: fixed header style issues/changed header descriptor
> LW-159: fixed header style issues/changed header descriptor

- components/common/header/descriptor.js
- components/common/header/index.tsx
- components/common/header/navbar-lang-selector/style.module.scss
- components/common/header/site-navbar/index.tsx
- components/common/header/site-navbar/style.module.scss
- lib/types/common.ts
- lib/xm/index.ts
- pages/index.tsx
- pages/kenaz/index.tsx
- pages/missl/index.tsx
chore: added header through XM for remaining pages
> LW-159: added header through XM for remaining pages

- components/common/footer/Footer.module.scss
- components/common/footer/index.tsx
- components/common/language-selector/index.tsx
> JIRA-00: footer ui issue resolved

- components/common/header/descriptor.js
- components/common/header/site-navbar/category-dropdown/index.tsx
- components/common/header/site-navbar/category-dropdown/style.module.scss
- components/common/header/site-navbar/index.tsx
- components/common/header/site-navbar/style.module.scss
chore: updated header descriptor
> LX-159: updated header descriptor

- .husky/pre-commit
- components/common/brands-card/brands-card.module.scss
- components/common/brands-card/index.tsx
- components/common/product-card/index.tsx
- styles/slider.scss
> Lw-166:explore our brands

- components/common/header/descriptor.js
- components/common/header/site-navbar/category-dropdown/index.tsx
- components/common/header/site-navbar/category-dropdown/style.module.scss
- components/common/header/site-navbar/style.module.scss
chore: updated styling for category drop down
> LW-159: updated styling for category drop down

- .husky/pre-commit
- components/common/header/index.tsx
- components/common/header/promo-bar/promo-base.test.tsx
- components/common/header/site-navbar/index.tsx
- components/common/header/site-navbar/style.module.scss
- lib/types/common.ts
- package.json
fixed: missing type prop added
> LW-159: missing type prop added

- components/common/header/navbar-lang-selector/style.module.scss
- components/common/header/site-navbar/category-dropdown/index.tsx
- components/common/header/site-navbar/category-dropdown/style.module.scss
- components/common/header/site-navbar/index.tsx
> LW-159: header styling fixes

- components/common/collection-card/index.module.scss
- components/common/collection-card/index.tsx
- styles/slider.scss
> LW-166: explore our collection

- components/common/header/mobile-navbar/style.module.scss
- components/common/header/user-navbar/brand-sidebar/brand-sidebar.module.scss
- components/common/header/user-navbar/brand-sidebar/index.tsx
> JIRA-00: arabic mobile menu

- components/common/header/mobile-navbar/style.module.scss
fix: mobile side bar pop in issue
> LW-159: mobile side bar pop in issue

- components/common/brand-cards/index.tsx
- components/common/header/mobile-navbar/style.module.scss
- components/common/header/user-navbar/brand-sidebar/brand-sidebar.module.scss
- components/xm-component-library.ts
mobile header & brand cards importing issue fixed
> JIRA-00: mobile header & brand cards importing issue fixed

- components/common/header/promo-bar/promo-bar.module.scss
fix: promo bar close button position issue
> LW-159: promo bar close button position issue

- components/common/header/descriptor.js
- components/common/header/index.tsx
- components/common/header/mobile-navbar/index.tsx
> JIRA-00: Mobile header

- components/common/header/user-navbar/brand-sidebar/index.tsx
- components/common/header/user-navbar/index.tsx
fix: removed unused imports/variables/code
> LW-159: removed unused imports/variables/code

- components/common/brand-cards/descriptor.js
> LW-160: styling of card

- components/common/header/user-navbar/brand-sidebar/brand-sidebar.module.scss
- components/common/header/user-navbar/brand-sidebar/index.tsx
- components/common/header/user-navbar/index.tsx
- components/common/header/user-navbar/user-navbar.module.scss
> LW-159: header styling issues

- components/common/header/mobile-navbar/mobile-sub-menu.tsx
- lib/types/mobile-header.ts
> JIRA-00: mobile navigation issue fixed

- styles/globals.scss
arabic footer arrow issue fixed
> JIRA-00: arabic footer arrow issue fixed

- components/common/card-slider/card-slider-test.tsx
- components/common/card-slider/index.tsx
- components/common/footer/footer-links/index.tsx
- components/common/footer/index.tsx
- components/icons/Account.tsx
- components/icons/ArrowRight.tsx
- components/icons/BackArrow.tsx
- components/icons/Bag.tsx
- components/icons/Calendar.tsx
- components/icons/CustomerCare.tsx
- components/icons/Heart.tsx
- components/icons/Location.tsx
- components/icons/MenuIcon.tsx
- components/icons/Search.tsx
- components/icons/SignOut.tsx
- lib/types/common.ts
> JIRA-00: unit testing

- components/common/header/navbar-lang-selector/navbar-lang-selector.module.scss
- components/common/ui/select/style.module.scss
fix: language selector font sizes issues
> LW-159: language selector font size issues

- components/common/footer/Footer.module.scss
- components/common/footer/index.tsx
- components/common/language-selector/index.tsx
- components/common/ui/select/index.tsx
- components/common/ui/select/style.module.scss
footer Lang drop-down font size fixes
> JIRA-00: footer lang dropdown font size fixes

- components/common/header/mobile-navbar/mobile-menu.tsx
- components/common/header/mobile-navbar/style.module.scss
- components/common/header/user-navbar/brand-sidebar/index.tsx
> JIRA-00: mobile header fixes

- components/common/ui/button/button.module.scss
fix: button arabic font family
> LW-158: button arabic font family

- components/common/header/mobile-navbar/style.module.scss
- components/common/header/user-navbar/brand-sidebar/brand-sidebar.module.scss
fix: missl text direction issue
> LW-159: missl text direction issue

- components/common/header/user-navbar/brand-sidebar/index.tsx
- components/common/header/user-navbar/index.tsx
- components/common/header/user-navbar/user-navbar.module.scss
- lib/mock-data/data.tsx
- lib/types/common.ts
- lib/types/mobile-header.ts
fix: ticker animation change/made clickable
> JIRA-00: ticker animation change/made clickable

- components/common/header/user-navbar/user-navbar.module.scss
fix: animation issue in header brand ticker
> LW-159: animation issue in header brand ticker

- components/common/ui/slider/slider.tsx
fix: slider direction issue on page refresh
> JIRA-00: slider direction issue on page refresh

- pages/index.tsx
chore: lazurde header title fix
> JIRA-00: lazurde header title fix

- components/common/brand-cards/Brand-cards.module.scss
- components/common/collection-card/index.module.scss
- components/common/hero-banner/Hero-banner.module.scss
- styles/slider.scss
> LW-160: UI fixes

- components/common/header/promo-bar/promo-bar.module.scss
> JIRA-00: promo bar cross fix

- components/common/header/promo-bar/promo-bar.module.scss
fix: promo-bar arabic font family fix
> LW-159: promo-bar arabic font family fix

- components/common/brand-cards/Brand-cards.module.scss
- components/common/collection-card/index.module.scss
- components/common/hero-banner/Hero-banner.module.scss
- components/common/plp-category/index.tsx
> LW-264: explore all category

- components/common/bambuser-ended-sessions/descriptor.js
- components/common/bambuser-ended-sessions/index.tsx
- components/common/bambuser-ended-sessions/styles.module.scss
chore: add bambuser-ended-sessions component
> chore: add bambuser-ended-sessions component

- components/common/banner/banner.module.scss
- components/common/banner/index.tsx
> LW-268 Category Banner

- components/common/banner/banner.module.scss
- components/common/brand-cards/Brand-cards.module.scss
- components/common/card-slider/style.module.scss
- components/common/card/card.module.scss
- components/common/collection-card/index.module.scss
- components/common/footer/Footer.module.scss
- components/common/footer/footer-icons-list/style.module.scss
- components/common/footer/footer-links/style.module.scss
- components/common/footer/index.tsx
- components/common/header/mobile-navbar/style.module.scss
- components/common/header/navbar-lang-selector/navbar-lang-selector.module.scss
- components/common/header/promo-bar/promo-bar.module.scss
- components/common/header/site-navbar/category-dropdown/style.module.scss
- components/common/header/site-navbar/style.module.scss
- components/common/header/user-navbar/brand-sidebar/brand-sidebar.module.scss
- components/common/header/user-navbar/user-navbar.module.scss
- components/common/hero-banner/Hero-banner.module.scss
- components/common/language-selector/style.module.scss
- components/common/plp-category/plp-category.module.scss
- components/common/product-card/ProductCard.module.scss
- components/common/product-listing/style.module.scss
- components/common/ui/accordion/Accordion.module.scss
- components/common/ui/button/button.module.scss
- components/common/ui/select/style.module.scss
- lib/mock-data/data.tsx
- styles/404.module.scss
- styles/slider.scss
- styles/variables.scss
> JIRA-00: style variables

- components/common/header/mobile-navbar/style.module.scss
- components/common/header/promo-bar/promo-bar.module.scss
- components/common/ui/accordion/Accordion.module.scss
- components/common/ui/select/style.module.scss
- styles/slider.scss
> JIRA-00: ui fixes for ios

- components/common/plp-category/plp-category.module.scss
> LW-268: Category Banner

- components/common/product-listing/filter-sorting-bar/index.tsx
- components/common/product-listing/filter-sorting-bar/style.module.scss
- pages/c/[...category_hierarchy].tsx
chore: filter bar clear filter button added
> LW-269: filter bar clear filter button added

- components/common/ui/modal/index.tsx
- pages/c/[...category_hierarchy].tsx
fix: filter mobile onClick fix/revert category_hierarchy test changes
> LW-269: filter mobile onClick fix/revert category_hierarchy test changes

- components/common/product-card/ProductCard.module.scss
> JIRA-00: wishlist icon show on hover

- components/common/product-listing/filter-sorting-bar/category-dropdown/index.tsx
- components/common/product-listing/filter-sorting-bar/category-dropdown/style.module.scss
- components/common/product-listing/filter-sorting-bar/index.tsx
- components/common/product-listing/filter-sorting-bar/style.module.scss
- components/common/product-listing/index.tsx
chore: adding filter api logic on plp page
> LW-269: adding filter api logic on plp page

- components/common/product-listing/filter-sorting-bar/index.tsx
> fix: reflect changes on dev

- components/common/product-card/ProductCard.tsx
- components/common/product-listing/index.tsx
- lib/mock-data/data.tsx
> LW-267: connected add to cart API

- components/common/footer/index.tsx
- components/common/header/navbar-lang-selector/index.test.tsx
- components/common/language-selector/index.test.tsx
- components/common/language-selector/index.tsx
- jest.config.js
footer logo specific for KSA region
> JIRA-00: footer logo specific for KSA region

- components/common/header/site-navbar/index.tsx
- components/common/header/site-navbar/style.module.scss
- components/common/plp-category/index.tsx
- components/common/product-listing/descriptor.js
- components/common/product-listing/filter-bar-mobile/dropdown/index.tsx
- components/common/product-listing/filter-bar-mobile/index.tsx
- components/common/product-listing/filter-sorting-bar/dropdown/index.tsx
- components/common/product-listing/filter-sorting-bar/index.test.tsx
- components/common/product-listing/filter-sorting-bar/index.tsx
- locales/ar-ae/common.json
- locales/ar-eg/common.json
- locales/ar-sa/common.json
- locales/ar/common.json
fix: filterbar descriptor fixes/unit testing
> LW-269: filterbar descriptor fixes/unit testing

- components/common/header/site-navbar/index.tsx
- components/common/header/site-navbar/site-navbar.test.tsx
- components/common/register-popup/register-popup.test.tsx
> JIRA-00: regiter pop up

- components/common/header/mobile-navbar/mobile-menu/mobile-menu.test.tsx
- components/common/header/mobile-navbar/mobile-menu/mobile-menu.tsx
- components/common/header/mobile-navbar/mobile-sub-menu/mobile-sub-menu.test.tsx
- components/common/header/promo-bar/promo-base.test.tsx
- components/common/header/site-navbar/category-dropdown/index.tsx
- components/common/header/site-navbar/index.tsx
- components/common/header/site-navbar/site-navbar.test.tsx
- components/common/product-listing/filter-bar-mobile/dropdown/index.test.tsx
- components/common/product-listing/filter-bar-mobile/dropdown/index.tsx
- components/common/product-listing/filter-bar-mobile/index.test.tsx
- components/common/product-listing/filter-sorting-bar/dropdown/index.test.tsx
- components/common/product-listing/filter-sorting-bar/dropdown/index.tsx
- components/common/product-listing/index.tsx
- components/icons/MinusIcon.tsx
- components/icons/PlusIcon.tsx
chore: improved unit test score for all low scoring components
> LW-269: improved unit test score for all low scoring components

- components/common/product-card/ProductCard.module.scss
- components/common/product-card/ProductCard.tsx
wish-list hide/show issue on product card
> JIRA-00: wishlist hide/show issue on product card

- components/common/plp-category/plp-category.module.scss
> JIRA-00: Cursor pointer

- components/common/product-listing/filter-bar-mobile/index.tsx
- components/common/product-listing/filter-bar-mobile/style.module.scss
- components/common/ui/borderless-select/index.tsx
- components/common/ui/borderless-select/style.module.scss
fix: added count for filter bar mobile
> LW-295: added count for filter bar mobile

- components/common/header/mobile-navbar/mobile-menu/mobile-menu.tsx
- components/common/header/site-navbar/index.tsx
- components/common/header/user-navbar/brand-sidebar/index.tsx
- components/common/header/user-navbar/index.tsx
- lib/utils/common.ts
- locales/ar-ae/common.json
- locales/ar-eg/common.json
- locales/ar-sa/common.json
- locales/ar/common.json
> JIRA-00: brand updates on app-state

- pages/missl/[...category_hierarchy].tsx
> JIRA-00: added missL plp page

- components/common/plp-category/index.tsx
> LW-305: url

- components/common/banner/banner.test.tsx
- components/common/footer/index.test.tsx
- components/common/header/mobile-navbar/index.test.tsx
- components/common/hero-banner/index.test.tsx
- components/common/plp-category/index.test.tsx
- components/common/plp-category/index.tsx
- components/common/register-popup/register-popup.test.tsx
- components/common/ui/modal/index.tsx
fix: improve coverage of unit test
> JIRA-00: improve coverage of unit test

- components/common/card-slider/descriptor.js
- components/common/card-slider/index.tsx
- components/common/card-slider/style.module.scss
- components/common/header/mobile-navbar/lang-selector/index.tsx
- components/common/language-selector/index.tsx
- lib/mock-data/data.tsx
- pages/kenaz/index.tsx
language selector changes for kenaz
> JIRA-00: language selector changes for kenaz

- components/common/help-category/descriptor.js
- components/common/help-category/index.tsx
- components/xm-component-library.ts
- pages/missl/c/[...category_hierarchy].tsx
> LW-86: Contact Us Page

- components/common/product-listing/filter-sorting-bar/index.tsx
fix: filter options list position bug
> LW-304: filter options list position bug

- components/common/plp-category/index.tsx
> LW-86: resolve conflicts

- components/common/help-category/descriptor.js
- components/common/help-category/help-category.module.scss
- components/common/help-category/index.tsx
fix: id of descriptor and styling of contact
> LW-86: id of descriptor and styling of contact

- .github/workflows/ci.yml
> LW-272: Api test in ci/cd

- components/common/bambuser-card-slider/index.tsx
- components/common/bambuser-card-slider/style.module.scss
- components/common/card/card.module.scss
> LW-263: ui fixes for bambuser slider

- components/common/header/user-navbar/user-navbar.test.tsx
- components/common/ui/pagination/index.tsx
fix: pagination data not refreshing on page change
> LW-266: pagination data not refreshing on page change

- components/common/hero-banner/Hero-banner.module.scss
- components/common/hero-banner/index.tsx
fix: replace image tag with img
> JIRA-00: replace image tag with img

- components/common/hero-banner/Hero-banner.module.scss
- components/common/hero-banner/index.tsx
fix: replace background image with next-image
> JIRA-00: replace background image with next-image

- components/common/card/index.test.tsx
- components/common/card/index.tsx
- components/common/footer/footer-icons-list/index.test.tsx
- components/common/footer/footer-icons-list/index.tsx
- components/common/footer/footer-links/index.tsx
- components/common/footer/index.test.tsx
- components/common/footer/index.tsx
> JIRA-00: Unit/testing

- components/common/feedback-popup/feedback-popup.module.scss
- components/common/feedback-popup/index.tsx
- components/common/help-category/descriptor.js
- components/common/help-category/help-category.module.scss
- components/common/help-category/index.tsx
> LW-86: height of blocks

- components/common/content-block/content-block.module.scss
- components/common/content-block/index.tsx
- components/common/terms-condition/index.tsx
- components/common/terms-condition/term-condition.module.scss
fix: term and condition component
> JIRA-00: term and condition component

- components/common/card/index.tsx
on-click sanity for card component
> JIRA-00: onclick sanity for card component

- components/common/header/navbar-lang-selector/index.tsx
- components/common/header/promo-bar/index.tsx
- components/common/header/promo-bar/promo-base.test.tsx
- components/common/header/user-navbar/brand-sidebar/brand-sidebar.module.scss
- components/common/header/user-navbar/brand-sidebar/index.tsx
- components/common/product-listing/index.tsx
- components/common/ui/pagination/index.tsx
> JIRA-00: plp filter logic fixes

- components/common/header/navbar-lang-selector/index.tsx
- components/common/header/navbar-lang-selector/navbar-lang-selector.module.scss
- components/common/header/promo-bar/promo-bar.module.scss
- components/common/language-selector/index.tsx
fix: lang selector show animation removed
> JIRA-00: lang selector show animation removed

- components/common/customer-service/descriptor.js
fix: customer Services component
> LW-104: customer Services component

- components/common/brand-cards/descriptor.js
- components/common/brand-cards/index.tsx
- components/common/card-slider/index.tsx
- components/common/collection-card/descriptor.js
- components/common/collection-card/index.tsx
- components/common/hero-banner/index.tsx
> JIRA-00: links issue of home page

- components/common/card-slider/index.tsx
- components/common/card/card.module.scss
- components/common/card/index.tsx
fixed the card slider link issue
> JIRA-00: fixed the card slider link issue

- components/common/product-listing/descriptor.js
- components/common/product-listing/index.tsx
- components/common/ui/bread-crumbs/index.tsx
- components/common/ui/bread-crumbs/style.module.scss
- components/xm-component-library.ts
> JIRA-00: LW-104

- components/common/ui/bread-crumbs/index.tsx
> JIRA-00: links on breadcrumb

- components/common/header/navbar-lang-selector/index.tsx
- components/common/header/promo-bar/index.tsx
- components/common/product-card/ProductCard.module.scss
- components/common/product-card/ProductCard.tsx
- components/common/search-dialog/index.tsx
- components/common/search-dialog/style.module.scss
- lib/context/index.tsx
search bar overlapping issue fixed
> LW-367: search bar overlapping issue fixed

- components/common/brand-cards/index.tsx
fix: Missing links on all the homepages and PLP pages.
> LW-370: Missing links on all the homepages and PLP pages.

- components/common/product-listing/index.tsx
- next.config.js
> LW-372: plp images slider issue fixed

- components/common/brand-cards/index.tsx
- styles/slider.scss
brand updates from brand-card links
> LW-373: brand updates from brand-card links

- components/common/product-listing/filter-bar-mobile/dropdown/style.module.scss
- components/common/product-listing/filter-sorting-bar/dropdown/style.module.scss
- components/common/search-dialog/index.tsx
- components/common/search-dialog/style.module.scss
search-bar & filter-bar issue fixed
> LW-373: searchbar & filterbar issue fixed

- components/common/product-listing/filter-sorting-bar/index.tsx
- components/common/product-listing/index.tsx
- components/common/product-listing/style.module.scss
fix: sorting and filter bar logic updates
> LW-374: sorting and filter bar logic updates

- components/common/header/user-navbar/brand-sidebar/index.tsx
brand issue fixed from sidebar
> LW-373: brand issue fixed from sidebar

- components/common/product-listing/filter-bar-mobile/index.tsx
- components/common/product-listing/filter-sorting-bar/index.tsx
> fix: added sort by data

- components/common/reviews/index.tsx
- components/common/reviews/style.module.scss
- components/common/reviews/write-review/index.tsx
- components/common/reviews/write-review/review-form.tsx
- components/common/reviews/write-review/style.module.scss
- components/common/ui/star-ratings/index.tsx
- components/common/ui/star-ratings/style.module.scss
- components/icons/FilledStar.tsx
- components/icons/Star.tsx
- components/icons/index.ts
- package.json
> LW-357: review section for pdp

- components/common/content-block/index.tsx
- components/common/terms-condition/descriptor.js
- components/common/terms-condition/index.tsx
- pages/help-centre/return-refund/index.tsx
- public/_descriptors.json
> LW-104: customer services

- components/common/product-listing/filter-bar-mobile/index.test.tsx
- components/common/product-listing/filter-bar-mobile/index.tsx
- components/common/product-listing/filter-sorting-bar/index.tsx
- components/common/product-listing/index.tsx
fix: updated filter logic - populate filter options dynamically
> LW-377: updated filter logic - populate filter options dynamically

- components/common/brand-cards/descriptor.js
- components/common/brand-cards/index.tsx
- components/common/card/index.tsx
fix: remove fav icon on brand card
> LW-379: remove fav icon on brand card

- components/common/content-block/content-block.module.scss
- components/common/content-block/index.tsx
- components/common/customer-service/descriptor.js
- components/common/customer-service/index.tsx
- components/common/terms-condition/descriptor.js
- components/common/terms-condition/index.tsx
- components/common/terms-condition/term-condition.module.scss
- public/_descriptors.json
> LW-104: refund policy component

- components/common/product-listing/index.tsx
> JIRA-00: plp data not populating

- components/common/product-listing/index.tsx
fix: product data not populating on plp
> JIRA-00: product data not populating on plp

- components/common/product-listing/index.tsx
fix: product data not updating on plp
> JIRA-00: product data not updating on plp

- components/common/product-listing/index.tsx
> LW-383: search bar sanity issue

- components/common/product-listing/index.tsx
> fix: console testing for plp

- components/common/product-listing/filter-sorting-bar/index.tsx
- components/common/product-listing/index.tsx
- pages/s.tsx
fix: brand and category filter logic changes for plp
> JIRA-00: brand and category filter logic changes for plp

- components/common/product-listing/index.tsx
- styles/globals.scss
fix: show message on empty product list
> JIRA-00: show message on empty product list

- components/common/product-listing/index.tsx
fix: plp filter sanities added
> JIRA-00: plp filter sanities added

- lib/algolia/index.ts
- lib/types/algolia.ts
> LW-392: fixed api page count

- components/common/reviews/index.tsx
- components/common/reviews/write-review/image-uploader.tsx
- components/common/reviews/write-review/review-form.tsx
- components/common/reviews/write-review/style.module.scss
- lib/utils/reviews.ts
> LW-357: write review API integration

- styles/globals.scss
outline fixed for all ios devices
> LW-395: outline fixed for all ios devices

- components/common/terms-condition/term-condition.module.scss
> fix: refund policy component

- components/common/product-card/ProductCard.tsx
- locales/ar-ae/common.json
- locales/ar-eg/common.json
- locales/ar-sa/common.json
- locales/ar/common.json
add-to-cart & exclusive-tag  button text in Arabic
> JIRA-00: add-to-cart & exclusiveTag  btn text in arabic

- components/common/product-listing/filter-bar-mobile/index.tsx
- components/common/product-listing/filter-bar-mobile/sorting-modal.tsx
- components/common/product-listing/filter-sorting-bar/index.test.tsx
- components/common/product-listing/filter-sorting-bar/index.tsx
- locales/ar-ae/common.json
- locales/ar-eg/common.json
- locales/ar-sa/common.json
- locales/ar/common.json
- locales/en-ae/common.json
- locales/en-eg/common.json
- locales/en-sa/common.json
- locales/en/common.json
fix: sorting not working in arabic
> LW-399: sorting not working in arabic

- components/common/product-listing/filter-bar-mobile/index.test.tsx
fix: test error in filter bar mobile
> fix: test error in filter bar mobile

- components/common/reviews/index.tsx
- components/common/ui/pagination/index.tsx
pagination added for review section
> LW-357: pagination added for review section

- components/common/ui/pagination/index.tsx
fix: re-adding removed pagination updates
> JIRA-00: re-adding removed pagination updates

- components/common/reviews/write-review/image-uploader.tsx
- components/common/reviews/write-review/index.tsx
review section img upload section
> LW-357: review section img upload section

- .github/workflows/ci.yml
- pages/_app.tsx
> UI/UX in ci/cd

- components/common/product-listing/index.tsx
- pages/s.tsx
> LW-401: searchbar jump issue fixed

- .github/workflows/ci.yml
> JIRA-00: Lazrude api tests

- components/common/product-description/image-section/image-section.module.scss
- components/common/product-description/index.tsx
- components/common/product-description/right-side-detail/index.tsx
- components/common/product-description/style.module.scss
> LW-414: product detail page structure

- components/common/product-description/right-side-detail/index.tsx
- components/common/ui/button/button.module.scss
- lib/xm/combine-descriptors.js
> LW-59: updated button type

- components/common/product-description/index.tsx
- components/common/product-description/right-side-detail/color-selection/index.tsx
- components/common/product-description/right-side-detail/color-selection/style.module.scss
- components/common/product-description/right-side-detail/index.tsx
- components/common/product-description/right-side-detail/size-selection/index.test.tsx
- components/common/product-description/right-side-detail/size-selection/index.tsx
- components/common/ui/button-add-to-cart/buttonATC.module.scss
- components/common/ui/button-add-to-cart/index.tsx
- lib/xm/combine-descriptors.js
- pages/c/[...category_hierarchy].tsx
chore: pdp page color selection component added
> LW-59: pdp page color selection component added

- components/common/header/promo-bar/promo-base.test.tsx
- components/common/product-description/image-section/image-section.module.scss
- components/common/product-description/image-section/index.tsx
- components/common/product-description/image-section/popup-image-view-v2/index.tsx
- components/common/product-description/image-section/popup-image-view-v2/popup-image-view-v2.module.scss
- components/common/product-description/style.module.scss
- components/common/ui/slider/slider.tsx
chore: pdp image section design change to v2
> LW-59: pdp image section design change to v2

- components/common/product-description/index.tsx
- components/common/product-description/right-side-detail/color-selection/index.tsx
- components/common/product-description/right-side-detail/color-selection/style.module.scss
- components/common/product-description/right-side-detail/index.tsx
- components/common/product-description/right-side-detail/size-selection/size-chart-modal.tsx
- components/common/product-description/right-side-detail/size-selection/style.module.scss
- components/common/product-description/style.module.scss
- components/common/reviews/write-review/style.module.scss
- components/common/ui/modal/modal.module.scss
- styles/variables.scss
> LW-414: product detail page fixes

- components/common/product-description/right-side-detail/color-selection/index.tsx
- components/common/product-description/right-side-detail/size-selection/index.tsx
- components/common/reviews/index.tsx
- components/common/reviews/review-tabs/index.tsx
- locales/ar-ae/common.json
- locales/ar-eg/common.json
- locales/ar-sa/common.json
- locales/ar/common.json
> JIRA-00: pdp styling

- components/common/product-card/ProductCard.module.scss
- components/common/product-description/right-side-detail/index.tsx
- components/common/product-description/right-side-detail/right-side-detail.module.scss
- components/common/ui/button-add-to-cart/buttonATC.module.scss
- components/common/ui/button-add-to-cart/index.tsx
- components/icons/MinusIcon.tsx
- components/icons/PlusIcon.tsx
> LW-59: pdp styling

- components/common/product-description/index.tsx
- components/common/product-description/right-side-detail/right-side-detail.module.scss
> LW-414: breadcrumb fixes

- components/common/reviews/style.module.scss
> LW-414: reviews styling

- components/common/product-description/index.tsx
- components/common/product-description/product-detail/index.test.tsx
- components/common/product-description/product-detail/index.tsx
- components/common/product-description/product-detail/style.module.scss
- components/common/product-description/right-side-detail/index.tsx
- components/common/product-description/right-side-detail/sub-detail/index.tsx
- components/common/ui/button-add-to-cart/index.tsx
> LW-414: product description fixes

- components/common/product-card/ProductCard.tsx
- components/common/product-description/right-side-detail/index.tsx
- lib/utils/cart.ts
redirect to cart page from plp
> JIRA-00: redirect to cart page from plp

- components/common/reviews/write-review/index.tsx
- components/common/reviews/write-review/review-form.tsx
- components/common/ui/alert/index.tsx
- components/icons/CrossSmall.tsx
- locales/ar-ae/common.json
- locales/ar-eg/common.json
- locales/ar-sa/common.json
- locales/ar/common.json
- styles/alert.scss
Arabic fixes for reviews section
> LW-436: arabic fixes for reviews section

- components/common/corporate-governance-and-investor-relations/index.tsx
- components/common/ui/modal/modal.module.scss
> JIRA-00: ui fixes

- components/common/product-description/right-side-detail/index.tsx
- components/common/product-description/right-side-detail/right-side-detail.module.scss
product not available issue fixed
> JIRA-00: product not available issue fixed

- components/common/product-description/right-side-detail/notify-me-modal/style.module.scss
> LW-436: notify me modal styling

- components/common/feedback-popup/index.tsx
> LW-450: contact us bugs

- components/common/product-card/ProductCard.tsx
> JIRA-00: wishlist on product card

- components/common/order-details/index.tsx
- components/common/product-description/right-side-detail/index.tsx
hide book an appointment and view button
> JIRA-00: hide book an appointment and view button

- components/common/cart/cart.module.scss
- components/common/cart/index.tsx
cart page structure & UI fixes
> LW-448: cart page structure & ui fixes

- components/common/account-information/index.tsx
- components/common/feedback-popup/feedback-popup.module.scss
- components/common/feedback-popup/index.tsx
- components/common/order-history/index.tsx
- components/common/order-history/order-history.module.scss
> LW-76: order details component

- components/common/cart-item/cart-item.module.scss
- components/common/cart-item/index.tsx
- components/common/cart/cart.module.scss
- components/common/cart/index.tsx
> LW-445: ui fixes for cart page

- components/common/customer-service/index.tsx
- components/common/product-description/right-side-detail/sub-detail/index.tsx
- components/common/reviews/write-review/review-form.tsx
UI fixes for product description
> LW-453: ui fixes for product description

- components/common/reviews/write-review/style.module.scss
> LW-453: ui fixes for review form

- components/common/celebrity-choice/celebrity-choice.module.scss
- components/common/celebrity-choice/index.tsx
- components/common/in-the-press/index.tsx
UI fixes for celebrities & in-the-press page
> JIRA-00: ui fixes for celebrities & inthepress page

- components/common/product-description/right-side-detail/index.tsx
- components/common/reviews/index.tsx
- components/common/reviews/write-review/style.module.scss
- components/common/ui/star-ratings/index.tsx
> JIRA-00: review form fixes

- components/common/in-the-press/in-the-press.module.scss
fix: in the press heading is aligned centre
> JIRA-00: in the press heading is aligned centre

- components/common/header/mobile-navbar/style.module.scss
fix: margin between   QR scan and text Hi San should be as per design
> LW-432: margin between   QR scan and text Hi San should be as per design

- components/common/header/mobile-navbar/style.module.scss
fix: button fixes for responsive
> JIRA-00: button fixes for responsive

- components/common/side-bar/side-bar.module.scss
fix: QR scan fixes for tablets view
> JIRA-00: QR scan fixes for tablets view

- components/common/content-block/index.tsx
fix: font size adjust for responsive
> JIRA-00: font size adjust for responsive

- components/common/corporate-governance-and-investor-relations/cgir.module.scss
> JIRA-00: button padding fixes

- components/common/side-bar/side-bar.module.scss
> JIRA-00: fixed as per breakpoint

- components/common/content-block/content-block.module.scss
- components/common/corporate-governance-and-investor-relations/cgir.module.scss
- components/common/corporate-governance-and-investor-relations/cgir.test.tsx
- components/common/corporate-governance-and-investor-relations/index.tsx
- components/common/order-details/index.tsx
- components/common/side-bar/index.tsx
- lib/utils/common.ts
> JIRA-00: quick ui fixes

- components/common/corporate-governance-and-investor-relations/cgir.module.scss
> JIRA-00: cgir button fixes

- components/common/content-block/index.tsx
- components/common/corporate-governance-and-investor-relations/cgir.module.scss
- components/common/corporate-governance-and-investor-relations/index.tsx
> JIRA-00: prospectus ui fixes

- components/common/account-information/account-reviews/product-without-reviews.tsx
- components/common/content-block/index.tsx
- components/common/corporate-governance-and-investor-relations/cgir.module.scss
- components/common/corporate-governance-and-investor-relations/index.tsx
- components/common/reviews/write-review/image-uploader.tsx
- components/common/reviews/write-review/review-form.tsx
Reverts shopistan/lazurde-storefront#700
> Revert "JIRA-00: merge develop to qa"

- components/common/content-block/index.tsx
- components/common/corporate-governance-and-investor-relations/cgir.module.scss
- components/common/corporate-governance-and-investor-relations/index.tsx
Reverts shopistan/lazurde-storefront#699
> Revert "JIRA-00: prospectus ui fixes"

- components/common/header/site-navbar/index.tsx
- components/common/search-dialog/index.tsx
- components/common/wishlist/index.tsx
- lib/context/index.tsx
> JIRA-00: sanity check issue fixed

- .env.local
> JIRA-00: xm url changed

- .env.local
> JIRA-00: xm url updated

- components/common/order-history/index.tsx
- components/common/order-history/order-history.module.scss
- components/common/ui/accordion/Accordion.module.scss
- lib/mock-data/data.tsx
> JIRA-00: order details fixes

- components/common/content-block/index.tsx
- components/common/corporate-governance-and-investor-relations/cgir.module.scss
- components/common/corporate-governance-and-investor-relations/index.tsx
> JIRA-00: update reverted code

- components/common/corporate-governance-and-investor-relations/cgir.module.scss
fix: update images gap for responsive
> JIRA-00: update images gap for responsive

- components/common/corporate-governance-and-investor-relations/cgir.module.scss
> JIRA-00: tablet pro ui fixes

- styles/globals.scss
fix: remove highlight for responsive
> JIRA-00: remove highlight for responsive

- components/common/corporate-governance-and-investor-relations/cgir.module.scss
- styles/globals.scss
> JIRA-00: merge develop to qa

- components/common/corporate-governance-and-investor-relations/cgir.module.scss
fix: prospectus ui fixes for responsive
> JIRA-00: prospectus ui fixes for responsive

- components/common/reviews/index.tsx
- components/common/reviews/style.module.scss
- components/common/reviews/write-review/image-uploader.tsx
- components/common/reviews/write-review/index.tsx
- components/common/reviews/write-review/review-form.tsx
reviews image upload issue fixed
> LW-469: reviews image upload issue fixed

- components/common/account-information/account-reviews/index.tsx
- components/common/account-information/account-reviews/style.module.scss
- components/common/account-information/index.tsx
- components/common/account-section/account-section.module.scss
- components/common/order-details/index.tsx
- components/common/side-bar/index.tsx
fix: account and order details fixes
> JIRA-00: account and order details fixes

- components/common/cart/index.tsx
> JIRA-00: update code

- components/common/order-details/index.tsx
- components/common/order-details/order-details.module.scss
- components/common/order-history/index.tsx
- components/common/order-history/order-history.module.scss
> JIRA-00: ui fixes for order detail

- components/common/account-information/index.tsx
- components/common/order-details/index.tsx
- components/common/side-bar/index.tsx
> JIRA-00: ui fixes for account page

- components/common/account-information/account-reviews/product-without-reviews.tsx
- components/common/account-information/account-reviews/style.module.scss
- styles/slider.scss
fix my Review page padding and height, width issues
> LW-485: fix my Review page padding and height, width issues

- components/common/account-information/index.tsx
- components/common/newsletter-subscriptions/index.tsx
- components/common/newsletter-subscriptions/style.module.scss
- locales/ar-ae/common.json
- locales/ar-eg/common.json
- locales/ar-sa/common.json
- locales/ar/common.json
> fix: News Letter Subscription page

- components/common/content-block/content-block.module.scss
- components/common/content-block/index.tsx
- components/common/terms-condition/index.tsx
- components/common/terms-condition/term-condition.module.scss
- pages/lazurde-policies.tsx
fix: terms and conditions updated
> JIRA-00: terms and conditions updated

- .env.local
- components/common/header/mobile-navbar/index.tsx
- components/common/minicart-wishlist-sidebars/mini-cart/index.test.tsx
- components/common/minicart-wishlist-sidebars/wish-list/index.test.tsx
xm url change & minicart unit tests
> LW-32: xm url change & minicart unit tests

- components/common/wishlist/my-wish-list/index.tsx
- components/common/wishlist/my-wish-list/style.module.scss
> JIRA-00: my wishlist bug fixes

- components/common/minicart-wishlist-sidebars/mini-cart/index.tsx
- components/common/minicart-wishlist-sidebars/style.module.scss
- components/common/ui/sidebar/sidebar.module.scss
- components/common/wishlist/my-wish-list/style.module.scss
mini-cart & account wish-list fixes
> LW-32: minicart & account wishlist fixes

- components/common/wishlist/my-wish-list/style.module.scss
> JIRA-00: my wishlist ui fixes

- components/common/content-block/content-block.module.scss
- components/common/terms-condition/term-condition.module.scss
- pages/lazurde-policies.tsx
fix: terms and conditions ui fixes
> JIRA-00: terms and conditions ui fixes

- components/common/reviews/index.tsx
- components/common/right-sidebars/account-sidebar/index.tsx
- components/common/right-sidebars/account-sidebar/login-links/index.tsx
- lib/utils/reviews.ts
account sidebar Arabic translation
> LW-77: account sidebar arabic translation

- components/common/right-sidebars/account-sidebar/index.tsx
- components/common/right-sidebars/account-sidebar/login-links/index.tsx
- components/icons/ArrowRight.tsx
- lib/mock-data/data.tsx
> LW-77: account sidebar fixes

- .github/workflows/ci.yml
> JIRA-00: Ci cd fixed

- components/common/content-block/content-block.module.scss
> LW-532: font sizes fixes

- components/common/corporate-governance-and-investor-relations/cgir.module.scss
> LW-533: cgir minor ui fixes

- .env.local
> JIRA-00: xm url change for uat

- components/common/account-information/index.tsx
- components/common/header/mobile-navbar/index.tsx
- components/common/header/user-navbar/index.tsx
- components/common/right-sidebars/account-sidebar/index.test.tsx
- components/common/right-sidebars/account-sidebar/index.tsx
- components/common/right-sidebars/account-sidebar/login-links/index.test.tsx
- components/common/right-sidebars/account-sidebar/login-links/index.tsx
- components/common/ui/button/index.tsx
- components/common/ui/heading/index.tsx
- lib/context/index.tsx
- lib/utils/cart.ts
unit testing & UI fixes for account page
> JIRA-00: unit testing & ui fixes for account page

- components/common/newsletter-subscriptions/index.tsx
- components/common/newsletter-subscriptions/style.module.scss
- pages/newsletter.tsx
> LW-79: newsletter updated

- components/common/header/user-navbar/index.tsx
- components/common/header/user-navbar/user-navbar.module.scss
- components/common/right-sidebars/account-sidebar/login-links/index.tsx
> JIRA-00: username on top navbar

- components/common/cart-item/index.tsx
- components/common/cart/index.tsx
- components/common/header/user-navbar/user-navbar.module.scss
- components/common/minicart-wishlist-sidebars/mini-cart/index.tsx
- components/common/minicart-wishlist-sidebars/style.module.scss
- components/common/minicart-wishlist-sidebars/wish-list/index.tsx
- components/common/product-card/ProductCard.tsx
- components/common/product-description/right-side-detail/index.tsx
- components/common/ui/sidebar/sidebar.module.scss
- components/common/wishlist/my-wish-list/index.tsx
- lib/context/index.tsx
- lib/utils/cart.ts
- pages/cart.tsx
> JIRA-00: dynamic cart id

- components/common/header/mobile-navbar/index.tsx
- components/common/header/mobile-navbar/style.module.scss
- components/common/header/user-navbar/index.tsx
- components/common/header/user-navbar/user-navbar.module.scss
- components/common/header/user-navbar/user-navbar.test.tsx
- components/common/minicart-wishlist-sidebars/mini-cart/index.tsx
- components/common/product-card/ProductCard.tsx
- components/common/product-description/right-side-detail/index.tsx
- lib/context/index.tsx
- lib/utils/cart.ts
> LW-537: mini cart flow changes

- components/common/product-description/right-side-detail/index.tsx
- components/common/reviews/index.tsx
- components/common/reviews/write-review/review-form/review-form.tsx
- lib/context/index.tsx
- lib/utils/cart.ts
> LW-545: out of stock/review changes

- components/common/register-popup/register-popup.test.tsx
- components/common/ui/modal/index.tsx
> JIRA-00: modal fixes

- components/common/corporate-governance-and-investor-relations/descriptor.js
> JIRA-00: update descriptor
